### ISSUE TITLE
Error just from adding in the first raster layer

### ISSUE THREAD

**Issue by ahaughan** [nextgis/qgis_molusce#22]
Hi,
I have just begun using MOLUSCE so apologies for any incorrect terminology or understanding. I am trying to conduct a change detection analysis from a 1995 land cover classification raster to a 2015 raster. I open MOLUSCE and select the 1995 year and get the following error:

Python error: An error has occurred while executing Python code: See message log (Python Error) for more details.

And the message log says this Python code:

2017-12-06T16:19:13	1	Traceback (most recent call last):
			  File "C:/Users/yh800249/.qgis2/python/plugins\molusce\moluscedialog.py", line 215, in 
 setInitialRaster
			    initRaster = Raster(unicode(layer.source()), 
 maskVals=utils.getLayerMaskById(self.initRasterId))
			  File "C:/Users/yh800249/.qgis2/python/plugins\molusce\algorithms\dataprovider.py", line 54, in __init__
			    if self.filename: self._read()
			  File "C:/Users/yh800249/.qgis2/python/plugins\molusce\algorithms\dataprovider.py", line 287, in _read
			    self.bands = np.ma.zeros((data.RasterCount,self.geodata['ySize'], self.geodata['xSize']), dtype=float)
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\numpy\ma\core.py", line 7887, in __call__
			    result = self._func.__call__(*args, **params).view(MaskedArray)
			MemoryError

Can anyone suggest what I might be doing wrong?

Thanks

**Comment by KolesovDmitry** [comment]
MemoryError shows issues with memory. MOLUSCE performs all processing steps in RAM, therefore the error happens if one (or more):
 * your computer doesn't have enough memory;
 * the rasters are 'big' and don't match free memory;
Try to check it, for example try to process a small raster (less pixels and less land-use classes).

**Comment by ahaughan** [comment]
Yes it does work with a smaller raster, thank you for the help!
