### ISSUE TITLE
MOLUSCE error

### ISSUE THREAD

**Issue by sreemanthrarupini** [nextgis/qgis_molusce#34]
I tried using the molusce plugin to forecast the water index (NDWI) for my study area. Can I use this plugin for this purpose? When I feed the initial year indices it shows the following error "The raster has a lot of variables. Does the raster store a nominal variable?" I have divided the index values into 4 classes.

**Comment by simgislab** [comment]
Try brand new MOLUSCE 4 for QGIS 3 and let us know if the problem persists. Reopen if necessary.
