### ISSUE TITLE
Factors raster is not set. Please specify them and try again

### ISSUE THREAD

**Issue by thiagoquinaia** [nextgis/qgis_molusce#36]
how i can define this factors ?

**Comment by nbr5** [comment]
May I know how you solved this problem, I am getting same error I am not getting what's wrong?

**Comment by simgislab** [comment]
Try brand new MOLUSCE 4 for QGIS 3 and let us know if the problem persists. Reopen if necessary.

**Comment by Olipakibuja** [comment]
I am using  MOLUSCE 4 in very recent Qgis software however i am still gettinf error. Please help me how tou solve this problem. Factors raster is not set. Please specify them and try again
