### ISSUE TITLE
Installing molusce plugin in qgis 2.18.28 in mx linux 19

### ISSUE THREAD

**Issue by mega12345678** [nextgis/qgis_molusce#37]
I try to install molusce plugin. I read that this plugin is trusted. When I continue to install, there is a message : The plugin is broken. Python said: Error Reading metadata: general. How to solve this?

**Comment by amsantac** [comment]
You can edit the metadata.txt file to solve it. I used the metadata.txt file from another plugin as example (the 'move' plugin) and it worked. Anyway, the Molusce plugin does not work well with QGIS 2.18.28 so you may need to try version 2.18.10 or earlier

**Comment by ivanbarsukov** [comment]
MOLUSCE 4.0 is available now. It works with QGIS 3

**Comment by mega12345678** [comment]
ok nice. I will try.
thank you
