### ISSUE TITLE
This shows up everytime i run the crosstable script. After adding the raster .

### ISSUE THREAD

**Issue by dubeyamit946** [nextgis/qgis_molusce#43]

**Comment by dubeyamit946** [comment]
The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

I am using profile.py

**Comment by Shinjita** [comment]
Hi, i am having the samw problem, do you how to fix?

**Comment by simgislab** [comment]
Try brand new MOLUSCE 4 for QGIS 3 and let us know if the problem persists. Reopen if necessary.
