### ISSUE TITLE
LULC prediction using MOLUSCE  shows Value error: operands could not be broadcast together with shapes (13,)(14,) in area change tab

### ISSUE THREAD

**Issue by BHAVNA66** [nextgis/qgis_molusce#44]
Hi, i am a PhD student and working on LULC changes. I am trying to use MOLUSCE. When I go to "Area Changes" tab, and I press the "Update tables" or "Create changes map", I always get the same python error message: -Python code: Value error: operands could not be broadcast together with shapes (13,)(14,).  would you help me? Thank you

**Comment by simgislab** [comment]
Try brand new MOLUSCE 4 for QGIS 3 and let us know if the problem persists. Reopen if necessary.
