### ISSUE TITLE
MOLUSCE plugin python memory error

### ISSUE THREAD

**Issue by G-0510** [nextgis/qgis_molusce#48]
hello guys, I m using Qgis 2.16 in windows 10. In using Molusce plugin i am facing problem in Validation tab the error shows is:-
MemoryError
Traceback (most recent call last):
File "C:/Users/gaurav jaiswal/.qgis2/python/plugins\molusce\moluscedialog.py", line 648, in startValidation
self.eb = EBudget(reference, simulated)
File "C:/Users/gaurav jaiswal/.qgis2/python/plugins\molusce\algorithms\models\errorbudget\ebmodel.py", line 90, in init
self.Sj[j] = 1.0*binaryzation(S, [j])
File "C:\PROGRA2\QGIS 2.16\apps\Python27\lib\site-packages\numpy\ma\core.py", line 3947, in rmul
return multiply(other, self)
File "C:\PROGRA2\QGIS 2.16\apps\Python27\lib\site-packages\numpy\ma\core.py", line 966, in call
result = self.f(da, db, *args, **kwargs)
MemoryError

Python version: 2.7.4 (default, Apr 6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]
QGIS version: 2.16.3 Nødebo, 7d00cae

I m not able to proceed further pls help me
Gaurav

**Comment by Liasartika** [comment]
I do have the same problem,, have you find the solution? I also have Nodebo version

**Comment by G-0510** [comment]
No i haven't got yet......in future if you get the solution pls let  me
know.

**Comment by avatar-007** [comment]
Maybe you don't have enough memory on drive C of your computer

**Comment by Liasartika** [comment]
I de extend my C drive and it has enough space I supposed but still doesn’t
work.
Has it work for you already?
If you found the solution, please let me know

**Comment by avatar-007** [comment]
I had the same problem when I had only 20GB of ram left on my COMPUTER's C drive, and it went away when I had 150GB of free ram on my computer's C drive. But I have a new problem, and I think you will have a new problem, and his（https://github.com/nextgis/molusce/issues/29#issuecomment-961581295） solution works.

**Comment by Liasartika** [comment]
Really? That big??? I need to allocate some space then. Ok, thank you so
much for your great advice. I’ll do it accordingly.

**Comment by avatar-007** [comment]
I have a new problem
Traceback (most recent call last):
			  File "C:/Users/avatar527/.qgis2/python/plugins\molusce\moluscedialog.py", line 467, in createChangeMap
			    self.analyst = AreaAnalyst(self.inputs["initial"], self.inputs["final"])
			  File "C:/Users/avatar527/.qgis2/python/plugins\molusce\algorithms\models\area_analysis\manager.py", line 59, in __init__
			    if second is None:
			ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by Liasartika** [comment]
I don’t have an issue with creating change map. Perhaps you can double
check if every legend has exactly the same name. Or if it isn’t the issue,
I hope you get the solution soon 🤞

**Comment by avatar-007** [comment]
Where did you download MOLUSCE? I loaded the MOLUSCE plugin directly in QGIS2.18.Is it the problem with the different versions？

**Comment by Liasartika** [comment]
I worked with qgis 2.16.3 Nodebo

**Comment by simgislab** [comment]
Try brand new MOLUSCE 4 for QGIS 3 and let us know if the problem persists
