### ISSUE TITLE
can not use in qgis3.x

### ISSUE THREAD

**Issue by liuchangmai** [nextgis/qgis_molusce#51]
i can't install succesfully
![image](https://github.com/nextgis/qgis_molusce/assets/91411157/a518e1ca-9609-4299-8145-862bab657fcc)
Traceback (most recent call last):
  File "D:\QGIS/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Administrator.DESKTOP-0LBSACG/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\molusce\__init__.py", line 29, in classFactory
    from molusce import MoluscePlugin
ImportError: cannot import name 'MoluscePlugin' from 'molusce' (C:\Users/Administrator.DESKTOP-0LBSACG/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\molusce\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "", line 1, in 
  File "D:\QGIS/apps/qgis-ltr/./python\pyplugin_installer\installer.py", line 672, in installFromZipFile
    if startPlugin(pluginName):
  File "D:\QGIS/apps/qgis-ltr/./python\qgis\utils.py", line 443, in startPlugin
    if not _startPlugin(packageName):
  File "D:\QGIS/apps/qgis-ltr/./python\qgis\utils.py", line 425, in _startPlugin
    _unloadPluginModules(packageName)
  File "D:\QGIS/apps/qgis-ltr/./python\qgis\utils.py", line 537, in _unloadPluginModules
    mods = _plugin_modules[packageName]
KeyError: 'molusce'

Python version:
3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]

QGIS version:
3.28.7-Firenze 'Firenze', fedae0eb52

Python path:
['D:/QGIS/apps/qgis-ltr/./python', 'C:/Users/Administrator.DESKTOP-0LBSACG/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python', 'C:/Users/Administrator.DESKTOP-0LBSACG/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins', 'D:/QGIS/apps/qgis-ltr/./python/plugins', 'D:\\QGIS\\apps\\grass\\grass82\\etc\\python', 'C:\\Program Files\\Hexagon\\ERDAS IMAGINE 2015\\usr\\lib\\Win32Release\\python', 'D:\\QGIS\\bin\\python39.zip', 'D:\\QGIS\\apps\\Python39\\DLLs', 'D:\\QGIS\\apps\\Python39\\lib', 'D:\\QGIS\\bin', 'D:\\QGIS\\apps\\Python39', 'D:\\QGIS\\apps\\Python39\\lib\\site-packages', 'D:\\QGIS\\apps\\Python39\\lib\\site-packages\\win32', 'D:\\QGIS\\apps\\Python39\\lib\\site-packages\\win32\\lib', 'D:\\QGIS\\apps\\Python39\\lib\\site-packages\\Pythonwin', 'C:/Users/Administrator.DESKTOP-0LBSACG/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python']

**Comment by Geosphatial** [comment]
i am also having similar problem. is there any fix or alternative?

**Comment by gomalhunzai** [comment]
please note the plugin can be only used in qgis2.x not qgis.3x. i also faced the issue with qgis.3x then i installed the 2.18 version.

**Comment by ivanbarsukov** [comment]
MOLUSCE 4.0 is available now. It works with QGIS 3
