### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by KKLOVESYEJI** [nextgis/qgis_molusce#52]
The plugin seems to be invalid or have unfulfilled dependencies. It has been installedbut can't be loaded. If you really need this plugin, you can contact its author or QGISusers group and try to solve the problem, If not, you can just uninstall it. Here is theerror message below:
The plugin is broken. Python said:
Non-ASCII character’\xe2 in file D:QGIS 2.18\apps\Python27\lib\sitepackages\scipy\stats continuous distns.py on line 3346, but no encodingdeclared: see http://python.org/dev/peps/pep-0263/ for details

**Comment by simgislab** [comment]
try using fresh new MOLUSCE 4 for QGIS 3
