### ISSUE TITLE
Issue adding tiff image to initial in molusce plugin

### ISSUE THREAD

**Issue by ranjitsaurav** [nextgis/qgis_molusce#8]
I have a vector file which i converted to raster from arcmap in tiff file format. I uploaded the tiff file in qgis in which I intended to use the molusce plugin. When I tried to add the tiff file in the initial of molusce plugin I got the message as "The raster have lots of different values.Does the raster store a nominal variable ?"

Can any one please suggest me why I am getting this message.

Thank you.

**Comment by simgislab** [comment]
did you add just one tif file?

**Comment by KolesovDmitry** [comment]
Hello, @ranjitsaurav Please, look at the comment https://github.com/nextgis/molusce/issues/4#issuecomment-98050794 and bellow. I think you have the same cause of the issue.

**Comment by ranjitsaurav** [comment]
Hi all,
Thank you very much for the reply. I do have multiple tiff files and all of them have the same issue. As I mentioned in the earlier post, the raster data is created from arcmap and have the data attributes in terms of "text". I have attached the screen shot of the raster file in arcmap.
This same file  I uploaded in qgis in which the data value is shown in terms of number. I have attached screen shot of the raster file in qgis also. 

I read the previous issue in which the data was continuous. So I assume since my data attribute was originally in term of "text" i am getting this issue in this plugin. Please correct me if I am wrong. Please suggest me if there is any workaround for this issue. 
Please let me know if I can send my tiff file to you.

Thank you very much for the help.

![raster1-arcmap](https://cloud.githubusercontent.com/assets/4898288/8545162/f683c764-24d5-11e5-834f-1166ec1354c1.png)
![raster2-qgis](https://cloud.githubusercontent.com/assets/4898288/8545170/036a96ce-24d6-11e5-85f5-16bda3ef95b7.png)

**Comment by simgislab** [comment]
sharing a couple of rasters that produce this error would definitely help.

**Comment by KolesovDmitry** [comment]
@ranjitsaurav how many different values are stored in the rasters? Are the values nominal?

Could you provide an example of your data?

**Comment by ranjitsaurav** [comment]
I could not attached my tiff file here so I send the tiff images in your respective email.
Please let me know if sending in email is ok.

Thank you very much for the help.

**Comment by KolesovDmitry** [comment]
Hello @ranjitsaurav , 
I checked your rasters, the values are quite strange for the plugin purposes:
 * the rasters contains 164 different values
 * there are a lot of rare values. For example **56** (34% !!!) values are **very** rare (less then 10 pixels). 

So I have to ask you some questions:

 * Do the values represents landuse classes? (One value = One landuse class)
 * Do you really need so lot of landuse classes?

I think you are doing something wrong with your data. (I'm not speaking about technically wrong, I mean 'logically' wrong).

Molusce constructs statistic models using your data. But to construct a statistic model using **all** of your values is almost impossible:  if a class has one-two samples only, we don't have statistics enough for modeling.

So if the rasters are really landuse data, I advise you to generalize the data (at least you need to remove all rare classes).

**Comment by ranjitsaurav** [comment]
Hi @KolesovDmitry,
Thank you very much for you help and suggestion. I will try to implement the raster file as you have suggested using proper landuse class like agricultural, forest etc. Actually the classes in my raster file is also landuse i.e the classes with 'A' as initial is all agricultural land. So I will try to merge these classes into one and try to use the tool again.

Thank you again for you suggestion.

**Comment by Breshit** [comment]
Hi
I have a same issue, but I'm using QGIS and my image is a file .tif, like this:

![help1](https://user-images.githubusercontent.com/26483698/40544247-fece2ade-5ffd-11e8-8ea9-072c2de55f32.png)

How can I select the values that appear the most?

**Comment by KolesovDmitry** [comment]
Hello, @Breshit 
really I don't know how to find the most frequent values using QGIS. Usually I use GRASS GIS for such things. But I'm not a QGIS user, I use it very rare. I'm sure there is a way to calculate frequencies of raster values using simple QGIS tools. For example try to create histogram for you raster in style dialog or something like it.

**Comment by parikhit2009** [comment]
Hello @KolesovDmitry, @ranjitsaurav 
I have tried a lot to create raster file from vector layer. I tried different way. But somehow the raster file is not accepting in MOLUSCE . I think I am doing something wrong from very basic. Can you please help me to sort it out. Please tell me how to do that from very first step. ( What should be the content of vector file, How it can be converted to raster file, how to store nominal data into that raster etc) .Its really urgent.

**Comment by Aurora1203** [comment]
Thanks for your great comments@KolesovDmitry. I still get another issue, it said that the raster geometry is different. I check them by using erase tool and overlaps etc. They are totally the same. ANy solution for it?

**Comment by simgislab** [comment]
Try brand new MOLUSCE 4 for QGIS 3 and let us know if the problem persists
