### ISSUE TITLE
area changes not calculating

### ISSUE THREAD

**Issue by jrozek** [nextgis/qgis_molusce#9]
I have two urban area maps-1991 and 2006.  The area changes calculates them as having the same land area and there is no change between them.  I have the no data value set at 0 for each one.  What is going wrong?

**Comment by KolesovDmitry** [comment]
Could you please provide your transition table? (Text version or a screenshot are both appropriate)

**Comment by jrozek** [comment]
Thanks so much for your response- I was able to get the Area Changes to be correct.  I am entirely new to using Molusce and am working on a final project for my Advanced GIS class.

I have a new problem that I don't think is data-related.  I can either run "update tables" or "create changes map" on the Area Changes tab but never both- the system either crashes or gives a "memory error" message if I try to do one after the other.  Unfortunately, you need to do both to move on with the process.  Any advice?

![classstatistics](https://cloud.githubusercontent.com/assets/16139645/11597146/c0d3c1e6-9a87-11e5-85e4-4622e7bc3eac.jpg)
![transitionmatrix](https://cloud.githubusercontent.com/assets/16139645/11597147/c2ad877c-9a87-11e5-8e11-740fce237125.jpg)

**Comment by bojanah345** [comment]
Hi! I've been experiencing similar problem: MOLUSCE calculates the class statistics and transition matrix correctly but as I hit the "Create changes map" button and specify the name of the resulting raster, QGIS crashes (Crash dumped). Every time. Any suggestions? Thank you!
(I'm using QGIS 2.14.1-Essen version but the problem occured with previous versions as well.)

**Comment by mazingaro** [comment]
The solution is reclassifications of values! 

After searching for the same answer answer as well I got responded by a user which write me: 
_An additional tip: a friend had labeled categories in their map with numbers 101, 102, 103, 201, 202, 203, 301, 302, 303, and Molusce was crashing. We found that reclassifying the categories to small numbers: 1, 2, 3, ..., 8, 9, solved the issue. Hope you find a solution soon. Best regards_﻿

Reclassification with r.reclass worked for me after 2 days of headache and searching for complicated solutions :)

**Comment by palarifeen** [comment]
Dear,
I have a problem during map validation for prediction purpose. I have added the screenshot. Please, suggest me to overcome the problem.
![Error during validation](https://user-images.githubusercontent.com/89900402/131784815-f8b02268-3e00-400d-86d5-fa975e4abf14.png)

**Comment by reinhartcjp** [comment]
Greetings!
When using MOLUSCE to generate Area Changes tables and map, I get an error message as stated. I have reclassified the features to one digit numbers and transform the raster from float to integer. Please help.

![Screenshot (108)](https://user-images.githubusercontent.com/81622295/138578109-78507f61-ccde-4943-9ec2-5f38b2cbecaf.png)

**Comment by cypressgithu** [comment]
> The solution is the reclassification of values!
> 
> After searching for the same answer answer as well I got responded by a user which wrote me: _An additional tip: a friend had labeled categories in their map with numbers 101, 102, 103, 201, 202, 203, 301, 302, 303, and Molusce was crashing. We found that reclassifying the categories to small numbers: 1, 2, 3, ..., 8, 9, solved the issue. Hope you find a solution soon. Best regards_﻿
> 
> Reclassification with r.reclass worked for me after 2 days of headache and searching for complicated solutions :)

Where is r.reclass exactly found

**Comment by cypressgithu** [comment]
How do l  configure Grass in QGIS 2.18

**Comment by mazingaro** [comment]
I don't use QGIS 2 so I cannot help you with this + this question lack
informations about your system, how did you install QGIS etc. In the mean
time, QGIS got it's own reclassification alghoritm. You can also use GRASS
GIS directly. So, I recommend you to do the reclassification in QGIS 3,
GRASS or whenever else you want and then use this results in Molusce.

**Comment by cypressgithu** [comment]
I have two urban landuse map which l classified using suppervised classification, with 3 classes each. 1 built-up, 2 unbuilt up and 3 water bodies.but lm having troubles creating a change map in MOLUSCE. 
![Screenshot (21)](https://user-images.githubusercontent.com/114870136/205169774-5d858cb5-4973-49af-a3fd-e0bbf864a4f4.png)
![Uploading Screenshot (21).png…]()

**Comment by cypressgithu** [comment]
> 

Thank you for your support, much appreciated.

**Comment by K5ola** [comment]
> 

Please I don't understand... Can use please elaborate it

**Comment by simgislab** [comment]
Try brand new MOLUSCE 4 for QGIS 3 and let us know if the problem persists
